name: CoShowroom & Regalos Sales

env:
  GOOGLE_SHEET_ID_COSHOWROOM: ${{ secrets.GOOGLE_SHEET_ID_COSHOWROOM }}
  GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
  GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
  GOOGLE_SHEET_ID_REGALOS: ${{ secrets.GOOGLE_SHEET_ID_REGALOS }}

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook
  schedule:
    - cron: '00 08 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm install
          npm start
